project:
  type: website

website:
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

editor: visual

